package tn.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-01-15T23:11:48.732+01:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://service.tn/", name = "GestionArticleWS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface GestionArticleWS {

    @WebResult(name = "return", targetNamespace = "http://service.tn/", partName = "return")
    @WebMethod
    public User returnUser(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );

    @WebMethod
    public void deleteUser(
        @WebParam(partName = "arg0", name = "arg0")
        UserDTO arg0
    );

    @WebResult(name = "return", targetNamespace = "http://service.tn/", partName = "return")
    @WebMethod
    public UserDTOArray getAllUser();

    @WebMethod
    public void updateUser(
        @WebParam(partName = "arg0", name = "arg0")
        UserDTO arg0
    );

    @WebResult(name = "return", targetNamespace = "http://service.tn/", partName = "return")
    @WebMethod
    public boolean findUser(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        UserDTO arg2
    );

    @WebMethod
    public void addArticle(
        @WebParam(partName = "arg0", name = "arg0")
        ArticleDTO arg0
    );

    @WebMethod
    public void updateArticle(
        @WebParam(partName = "arg0", name = "arg0")
        ArticleDTO arg0
    );

    @WebResult(name = "return", targetNamespace = "http://service.tn/", partName = "return")
    @WebMethod
    public ArticleDTOArray getAllArticle();

    @WebMethod
    public void deleteArticle(
        @WebParam(partName = "arg0", name = "arg0")
        ArticleDTO arg0
    );
}
